In [1]:
import numpy as np

In [9]:
a = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4])

In [6]:
a.shape

(5,)

In [7]:
a.ndim

1

In [10]:
b = np.array([[0, 1, 2], [3, 4, 5]]) 

In [11]:
b

array([[0, 1, 2],
       [3, 4, 5]])

In [12]:
c = np.ones((4,4), dtype="bool")

In [13]:
c

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [14]:
c[2,1]=0

In [15]:
c

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True, False,  True,  True],
       [ True,  True,  True,  True]])

In [17]:
s = np.diag([1, 1, 1, 1])
s

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [18]:
s = np.diag([1,1,1,1],-1)
s

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0]])

In [19]:
a = np.random.rand(4)
a

array([0.20230769, 0.77004507, 0.95845461, 0.04423938])

In [23]:
np.random.seed(3447)
np.random.rand(5)

array([0.77155069, 0.67219888, 0.85061675, 0.470299  , 0.65209927])

In [24]:
np.may_share_memory(a,s) # a, s has the same reference in memory?

False

In [25]:
w = np.array([[1,2,3], [2,1,3], [1,4,5]])

In [26]:
t = w[1:3].copy()

In [28]:
np.may_share_memory(w,t)

False

In [32]:
mask = np.ones((3,3), dtype="bool")
mask

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [33]:
mask[2]=0
mask

array([[ True,  True,  True],
       [ True,  True,  True],
       [False, False, False]])

In [34]:
p = w[mask]
p

array([1, 2, 3, 2, 1, 3])

In [35]:
np.may_share_memory(p,w)

False

In [ ]:
np.random.seed(3)
a = np.random.randint(0, 21, 15)